name             'upload'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures upload'
long_description 'Installs/Configures upload'
version          '0.1.0'
