
source "https://supermarket.chef.io"

metadata

cookbook "chef-server-ha-aws-provisioner"

cookbook "chef-ingredient"

cookbook "chef-server"
cookbook "aws"
cookbook "aws_security"
cookbook 'route53', '~> 0.4.4'
